### ISSUE TITLE
NFL QB Club 32X

### ISSUE THREAD

**Issue by DaleNixon** [libretro/picodrive#187] opened 2021-11-20 03:11 UTC
In NFL Quarterback Club for 32x team icons are not displayed in Picodrive.

**Comment by irixxxx** [comment] 2021-11-20 08:37
Which platform and which version did you use?

**Comment by irixxxx** [comment] 2021-11-20 09:04
Confirmed with standalone linux version. Presumably no VDP graphics problem, sprites list is empty.

**Comment by irixxxx** [comment] 2021-11-20 13:45
Old bug, this dates back at least to 1.93.

**Comment by irixxxx** [comment] 2021-11-21 19:57
I uses an MD background in H32 mode. That wasn't officially supported by Sega on 32X and is currently unsupported by picodrive.

**Comment by irixxxx** [comment] 2021-11-22 18:25
fixed by 52e4a90 in my repo. In lr-picodrive with the next merge. This may take a while since I just merged 1.99.

**Comment by DrUm78** [comment] 2021-11-22 20:21
Confirmed to work on the FunKey S! Thanks!

Before:

![IMG_0130](https://user-images.githubusercontent.com/46139740/142929554-f8307d69-921a-49e9-bb4e-b4a74d120844.PNG)

After:

![IMG_0133](https://user-images.githubusercontent.com/46139740/142929596-efeea11a-b0c6-4f0c-9371-7f9a55f6fba4.PNG)

**Comment by irixxxx** [comment] 2021-12-29 15:31
merged.

**Closed by irixxxx** 2021-12-29 15:31 UTC
